### PR TITLE
Update Gradle Wrapper, Loom, Minotaur and FAPI

### LINKED ISSUE #1: [bug] on 1.20.2, appears to work at first, but crashes after using portal twice.
This is the error I see in console:

```
[21:50:20] [Immersive Cursedness Thread/ERROR] (FabricLoader) Uncaught exception in thread "Immersive Cursedness Thread" java.lang.NoSuchMethodError: 'net.minecraft.class_2540 net.minecraft.class_2540.method_10794(net.minecraft.class_2487)'
        at nl.theepicblock.immersive_cursedness.PlayerManager.lambda$tick$2(PlayerManager.java:145) ~[immersive-cursedness-1.5.0.jar:?]
        at nl.theepicblock.immersive_cursedness.objects.FlatStandingRectangle.iterateClamped(FlatStandingRectangle.java:120) ~[immersive-cursedness-1.5.0.jar:?]
        at nl.theepicblock.immersive_cursedness.PlayerManager.tick(PlayerManager.java:115) ~[immersive-cursedness-1.5.0.jar:?]
        at nl.theepicblock.immersive_cursedness.CursednessServer.lambda$tick$1(CursednessServer.java:65) ~[immersive-cursedness-1.5.0.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at nl.theepicblock.immersive_cursedness.CursednessServer.tick(CursednessServer.java:64) ~[immersive-cursedness-1.5.0.jar:?]
        at nl.theepicblock.immersive_cursedness.CursednessServer.start(CursednessServer.java:36) ~[immersive-cursedness-1.5.0.jar:?]
        at nl.theepicblock.immersive_cursedness.ImmersiveCursedness.lambda$onInitialize$0(ImmersiveCursedness.java:26) ~[immersive-cursedness-1.5.0.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

This doesn't stop the server, so I assume it's just crashing the Immersive Cursedness thread?

Edit: this seems to happen when I go through the portal in the nether -> overworld direction.

### PR DESCRIPTION
**Pull request by Obydux**
This fixes #1 and makes the mod work on >=1.20.2

### CODE REVIEW

**Comment by configari** [comment]
If possible can this be updated to 1.21.4? Thank you.
